
export const GET_CONTACTS_LOAD= "GET_CONTACTS_LOAD"
export const GET_CONTACTS_SUCC= "GET_CONTACTS_SUCC"
export const GET_CONTACTS_FAIL= "GET_CONTACTS_FAIL"

export const DELETE_CONTACT_SUCC= "DELETE_CONTACT_SUCC"
export const DELETE_CONTACT_FAIL= "DELETE_CONTACT_FAIL"


export const ADD_CONTACTS_SUCC= "ADD_CONTACTS_SUCC"
export const ADD_CONTACTS_FAIL= "ADD_CONTACTS_FAIL"

export const TOGGLE_TRUE="TOGGLE_TRUE"
export const TOGGLE_FALSE="TOGGLE_FALSE"

export const ADD_CONTACTS_SUCC= "ADD_CONTACTS_SUCC"
export const ADD_CONTACTS_FAIL= "ADD_CONTACTS_FAIL"

export const GET_CONTACT_LOAD= "GET_CONTACT_LOAD"
export const GET_CONTACT_SUCC= "GET_CONTACT_SUCC"
export const GET_CONTACT_FAIL= "GET_CONTACT_FAIL"

export const EDIT_CONTACTS_SUCC= "EDIT_CONTACTS_SUCC"
export const EDIT_CONTACTS_FAIL= "EDIT_CONTACTS_FAIL"